nohup Rscript trafficScript_car.R > nohup_car.out
nohup Rscript trafficScript_2_w.R > nohup_2_w.out
nohup Rscript trafficScript_3_w.R > nohup_3_w.out
nohup Rscript trafficScript_bus.R > nohup_bus.out
nohup Rscript trafficScript_cyp.R > nohup_cyp.out
nohup Rscript trafficScript_hcv.R > nohup_hcv.out
nohup Rscript trafficScript_lcv.R > nohup_lcv.out
nohup Rscript trafficScript_minibus.R > nohup_minibus.out
nohup Rscript trafficScript_others.R > nohup_others.out